# Generated by Django 2.2 on 2019-04-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID')
                ),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('details', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('visitors', models.IntegerField()),
                ('request_date', models.DateTimeField(
                    verbose_name='date requested')
                ),
                ('approval_uuid', models.UUIDField()),
                ('approved', models.BooleanField(
                    default=False)
                ),
                ('approval_date', models.DateTimeField(
                    verbose_name='date approved')
                ),
            ],
        ),
    ]
