# Generated by Django 2.2 on 2019-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('details', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('visitors', models.IntegerField()),
                ('request_date', models.DateTimeField()),
                ('approval_uuid', models.UUIDField()),
                ('approved', models.BooleanField(
                    default=False)
                ),
                ('approval_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
