# Generated by Django 2.2 on 2019-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickering', '0002_auto_20190518_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
